name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run ktLint
        run: ./gradlew lintKotlin

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test